version: 2
jobs:
  crowdin-upload:
    docker:
      - image: dougley/crowdin
    steps:
      - checkout
      - run: crowdin upload sources
  test:
    docker:
      - image: node:chakracore-10.13.0
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install modules
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
  deploy:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run: git remote add dokku dokku@$DOKKU_SERVER_ADDRESS:switchblade-$CIRCLE_BRANCH
      - run: ssh-keyscan -H $DOKKU_SERVER_ADDRESS >> ~/.ssh/known_hosts
      - run: git push -q -f dokku $CIRCLE_BRANCH:master

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: /master|dev/
  deploy:
    jobs:
      - test:
          filters:
            branches:
              only: /master|dev/
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: /master|dev/
  crowdin:
    jobs:
      - crowdin-upload:
          filters:
            branches:
              only: /dev/
